spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/userpwd?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://39.103.163.45:3306/userpwd?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
